[project]
name = "cerebrus-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "assemblyai>=0.46.0",
    "assemblyai-haystack>=0.1.1",
    "elasticsearch-haystack>=4.1.0",
    "fastapi[standard]>=0.121.2",
    "fastembed-haystack>=1.5.0",
    "firecrawl>=4.8.0",
    "google-genai>=1.50.1",
    "google-genai-haystack>=2.2.0",
    "haystack-ai>=2.20.0",
    "ipykernel>=7.1.0",
    "markdown-it-py>=4.0.0",
    "mdit-plain>=1.0.1",
    "nltk>=3.9.2",
    "pylint>=4.0.3",
    "pypdf>=6.2.0",
    "pytest>=9.0.1",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.15.1",
    "qdrant-haystack>=9.3.0",
    "ruff>=0.14.5",
    "sentence-transformers>=5.1.2",
    "streamlit>=1.51.0",
    "structlog>=25.5.0",
    "websockets>=15.0.1",
    "yt-dlp>=2025.11.12",
]
